<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{2bbb03aa-d457-41dc-adf0-3baf372f675a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AlarmManager();
GVL.event_initialized := AlarmManager.init;
UserProgram();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="1562" Count="0" />
      <LineId Id="1455" Count="0" />
      <LineId Id="1561" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>